name: Frontend CI

on:
  push:
    paths:
      - 'payflex-frontend/**'
      - '.github/workflows/frontend-ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: payflex-frontend

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build
